In [8]:
#1. Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
Null = np.zeros(10)
Null[4] = 1
print(Null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
#2. Create a vector with values ranging from 10 to 49.
X = np.arange(10,49)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8.
np.random.randint(0,8,(3,3))

array([[1, 7, 0],
       [0, 5, 6],
       [2, 0, 6]])

In [40]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

a = np.array([1,2,0,0,4,0])
a[a>0]

array([1, 2, 4])

In [22]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
m = np.random.rand(10,10)
print('Maximum value :',np.max(m))
print('Minimum value :',np.min(m))

Maximum value : 0.9916176569882152
Minimum value : 0.000525183644429994


In [29]:
#6. Create a random vector of size 30 and find the mean value.
vector = np.random.randint(0,150,(10,3))
print(vector)
print('Mean :',np.mean(vector,0))

[[ 44  37 133]
 [ 95  71 136]
 [135  54 108]
 [ 61  13 100]
 [ 61 132   3]
 [  0 126 125]
 [  6  86  35]
 [ 12  33  40]
 [135 145 111]
 [120  56  17]]
Mean : [66.9 75.3 80.8]
