In [ ]:
#Q1. Write a program to find all pairs of an integer array whose sum is equal to a given number?

#Q2. Write a program to reverse an array in place? In place means you cannot create a new array. You have to update the original array.

#Q3. Write a program to check if two strings are a rotation of each other?

#Q4. Write a program to print the first non-repeated character from a string?

#Q5. Read about the Tower of Hanoi algorithm. Write a program to implement it.

#Q6. Read about infix, prefix, and postfix expressions. Write a program to convert postfix to prefix expression.

#Q7. Write a program to convert prefix expression to infix expression.

#Q8. Write a program to check if all the brackets are closed in a given code snippet.

#Q9. Write a program to reverse a stack.

#Q10. Write a program to find the smallest number using a stack.

In [1]:
#Q1. Write a program to find all pairs of an integer array whose sum is equal to a given number?    

In [26]:
import numpy as np

In [37]:
def count_pairs(arr,sum):
    count = 0
    for i in range(0,len(arr)):
        for j in range(i+1,len(arr)):
            if (arr[i]+arr[j] == sum):
                count+=1
    return count

arr = np.array(list(map(int,input().split())))
#n = len(arr)
sum = int(input())
count_pairs(arr,sum)

1 5 7 -1 7
6


3

In [38]:
#Q2. Write a program to reverse an array in place? In place means you cannot create a new array. You have to update the original array.

In [39]:
arr = np.array(list(map(int,input().split())))
arr = arr[::-1]
print(arr)

1 2 3 4 5 6 7
[7 6 5 4 3 2 1]


In [40]:
#Q3. Write a program to check if two strings are a rotation of each other?

In [65]:
def findStringRotation(s1,s2):
    temp = ''
    if len(s1)!=len(s2):
        return False
    else:
        temp = s1+s2
        if temp.count(s2)>=0:
            return True
        else:
            return False

In [69]:
s1 = "abcdef"
s2 = "cdefab"
findStringRotation(s1,s2)

True

In [70]:
#Q4. Write a program to print the first non-repeated character from a string?

In [93]:
def first_non_rep_chr(string1):
    char = {}
    for i in range(len(string1)):
        key = string1[i]
        if key not in char:
            char[key] = 1
        else:
            char[key] = char[key]+1
    
    for key,value in char.items():
        if value == 1:
            print(key)
            break

In [94]:
first_non_rep_chr('nithin')

t


In [95]:
#Q5. Read about the Tower of Hanoi algorithm. Write a program to implement it.

In [97]:
def div1(x,y):
    print ('%s/%s = %s' % (x, y, x/y))
def div2(x,y):
    print

In [99]:
div1(5.,2.)

5.0/2.0 = 2.5


In [106]:
class parent(ABC):
    def common(self):
        print('Parent1')
    @abstractmethod
    def vary(self):
        pass
class child(parent):
    def vary(self):
        print('Child1')
obj = child()
obj.common()
obj.vary()

NameError: name 'ABC' is not defined

In [4]:
import numpy as np
samplearray = np.random.random_sample((3, 3))
print(samplearray)

[[0.08630851 0.22094155 0.52018307]
 [0.55285749 0.34682563 0.94376393]
 [0.965024   0.71176796 0.41744004]]


In [5]:
import pandas as pd
first_series = pd.Series([1, 2, 3, 4, 6])
second_series = pd.Series([5, 6, 7, 8])
a = first_series[-first_series.isin(second_series)]
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [6]:
sample_series = pd.Series(np.random.randint(1, 30, 9))
data_frame = pd.DataFrame(sample_series.values.reshape(3,3))
print(data_frame)

    0   1   2
0  20  22   3
1  11  26  28
2  25  14   2


In [7]:
numbers = np.array([[5,8,3],
                    [3,1,2],
                    [5,7,8]])
print("Which row and column?",numbers[1][2])

Which row and column? 2
